services:
  postgres:
    container_name: book-network-api-2-postgres
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_network
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - book-network-api-2-network
    restart: unless-stopped

  mail-dev:
    container_name: book-network-api-mail-dev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  book-network-api-2-network:
    driver: bridge

volumes:
  postgres:
    driver: local